/**
 * The dev server's view of the API: which scheme the `/api` proxy targets, and
 * whether the dev server itself is HTTPS.
 *
 * Both answers are derived from files outside this project — `certs/` in the
 * repository root and `TLS_ENABLED` in `server/.env` — and both being wrong is
 * invisible in the code and obvious on screen:
 *
 *   • proxy target `http://localhost:5000` against an API answering on HTTPS is
 *     a TLS handshake against a plaintext listener. Every request 502s, and the
 *     error names neither TLS nor the certificate, so the first conclusion is
 *     that the certificate is broken. It is not.
 *   • an https dev server with a plaintext API is refused by the browser as
 *     mixed content, before the request is sent. Same total failure, same
 *     unhelpful message.
 *
 * So these are asserted against the real config, not against a copy of the rule.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { X509Certificate } from 'node:crypto';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(here, '..', '..');
const repoRoot = resolve(appRoot, '..');
const certDir = join(repoRoot, 'certs');

const hasCertificate = existsSync(join(certDir, 'localhost.pem'))
  && existsSync(join(certDir, 'localhost-key.pem'));

// Imported through a file URL: Vite's config runs `import.meta.url` logic and a
// bare relative specifier is not resolvable here on Windows.
const configModule = await import(pathToFileURL(join(appRoot, 'vite.config.js')).href);
const config = configModule.default({ command: 'serve' });

test('the dev server uses HTTPS when a certificate is present', { skip: !hasCertificate && 'run `npm run certs` first' }, () => {
  assert.ok(config.server.https, 'server.https should carry the certificate');
  assert.ok(config.server.https.cert, 'server.https should carry the certificate chain');
  assert.ok(config.server.https.key, 'server.https should carry the private key');
  // A private key has to actually be a key. Vite accepts a string here and
  // fails at handshake time otherwise, which is a much worse place to find out.
  assert.match(String(config.server.https.key), /PRIVATE KEY/);
});

test('preview serves HTTPS too, because preview is how a build gets checked', { skip: !hasCertificate && 'run `npm run certs` first' }, () => {
  assert.ok(config.preview.https, 'preview should use the same certificate as dev');
});

test('the proxy targets the scheme the API is actually serving', () => {
  // This is the assertion that matters most: the two MUST agree, and the only way
  // to know is to read the server's own configuration the way the config does.
  const serverEnv = readServerEnv();
  const apiUsesTls = serverEnv === null
    ? false
    : String(serverEnv).trim().replace(/^["']|["']$/g, '').toLowerCase() === 'true';

  const expected = apiUsesTls ? 'https://localhost:5000' : 'http://localhost:5000';
  assert.equal(
    config.server.proxy['/api'].target,
    expected,
    `server/.env says TLS_ENABLED=${serverEnv}, so the proxy must target ${expected}`,
  );
});

test('the proxy verifies the API certificate rather than skipping verification', { skip: !hasCertificate && 'run `npm run certs` first' }, () => {
  const proxy = config.server.proxy['/api'];
  if (!proxy.target.startsWith('https://')) {
    // Nothing to verify against a plaintext target.
    assert.equal(proxy.secure, undefined, 'no HTTPS target, so no verification setting expected');
    return;
  }
  // `secure: false` would make every proxied request succeed regardless of which
  // certificate the API presents — including somebody else's. The CA is passed
  // instead, which teaches Node one extra trusted issuer and leaves the checks on.
  assert.notEqual(proxy.secure, false, 'the proxy must not disable certificate verification');
  assert.ok(proxy.ca, 'the proxy should be given the development CA');
});

test('the certificate covers the hosts this setup actually uses', { skip: !hasCertificate && 'run `npm run certs` first' }, () => {
  // The certificate is generated by scripts/dev-certs.mjs, so this is mostly an
  // assertion about that script having been run with the right hosts. It matters
  // because the phone-on-Wi-Fi case reaches https://192.168.x.x:5000, and a
  // certificate valid only for localhost is refused there with an error that
  // looks like the phone's problem rather than the certificate's.
  // Node parses the certificate itself. Reading the SANs out of the raw DER by
  // searching for text would be wrong anyway: a DNS name is stored as text but
  // an IP address is stored as four bytes, so `127.0.0.1` never appears
  // literally and a text search silently passes on the wrong host set.
  const certificate = new X509Certificate(readFileSync(join(certDir, 'localhost.pem')));
  const san = certificate.subjectAltName || '';
  assert.match(san, /DNS:localhost/, 'the certificate should be valid for localhost');
  assert.match(san, /IP Address:127\.0\.0\.1/, 'the certificate should be valid for 127.0.0.1');
});

/** TLS_ENABLED as written in server/.env, or null when there is no such file. */
function readServerEnv() {
  const envFile = join(repoRoot, 'server', '.env');
  if (!existsSync(envFile)) return null;
  for (const line of readFileSync(envFile, 'utf8').split(/\r?\n/)) {
    const match = /^\s*TLS_ENABLED\s*=\s*(.*)$/.exec(line);
    if (match) return match[1].trim();
  }
  return null;
}

