const mongoose = require('mongoose');
const crypto = require('crypto');

/**
 * Single-use password-reset grants, in MongoDB.
 *
 * WHY THIS IS A MODEL AND NOT A MAP
 * ---------------------------------
 * The previous implementation kept reset codes in a module-level `Map` inside
 * routes/auth.js, with a comment admitting "in production, use Redis or
 * database". Three real consequences, all of them user-facing:
 *
 *   1. nodemon restarts, a deploy, or a second process silently destroyed every
 *      outstanding code. A user who had the mail open, ready to type the code,
 *      was told "No password reset request found" — with nothing they could do
 *      about it and no way to tell that wasn't their fault.
 *   2. Nothing survived a crash, so the flow could not be tested against a real
 *      database, and the only integration tests were ones that stubbed
 *      `User.findOne`.
 *   3. The map held the code in PLAINTEXT for the whole 10-minute window.
 *
 * This stores only SHA-256 digests, and MongoDB's TTL index removes spent and
 * expired rows on its own — there is no sweeper interval to leak or to forget.
 *
 * TWO SECRETS PER GRANT
 * ---------------------
 * Each grant carries a 256-bit random `token` (the emailed link) AND a 6-digit
 * `code`. The link is the flow. The code exists so a person who cannot click —
 * a phone reading the mail on another device, a client that strips links, an
 * accessibility tool that only surfaces text — is not locked out of their own
 * account. A 6-digit code is only ~20 bits, so it is NOT the primary
 * credential: it is rate-limited per account, attempt-capped, and only ever
 * accepted alongside an unguessable token flow. The hashed-stored property that
 * makes `token` safe does not make `code` safe, which is why the code path
 * keeps its own brute-force accounting.
 */

const RESET_TOKEN_BYTES = 32; // 256 bits
const RESET_CODE_MIN = 100000;
const RESET_CODE_MAX = 999999;

/** Digest a secret for storage. Tokens are high-entropy, so a plain hash is right. */
function hashSecret(value) {
  return crypto.createHash('sha256').update(String(value), 'utf8').digest('hex');
}

/** Length-safe, timing-safe hex comparison. */
function constantTimeEqualsHex(a, b) {
  const left = Buffer.from(String(a || ''), 'hex');
  const right = Buffer.from(String(b || ''), 'hex');
  // timingSafeEqual THROWS on a length mismatch, which is itself a timing
  // signal, so the length check comes first and both branches return the same.
  if (left.length === 0 || left.length !== right.length) return false;
  return crypto.timingSafeEqual(left, right);
}

/** Fresh secrets. Generated by the caller so the mail can go out BEFORE storage. */
function generateSecrets() {
  return {
    token: crypto.randomBytes(RESET_TOKEN_BYTES).toString('base64url'),
    code: crypto.randomInt(RESET_CODE_MIN, RESET_CODE_MAX).toString(),
  };
}

const passwordResetTokenSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    // select:false on both digests so a stray `.find()` can never serialize
    // them into an API response or a log line.
    tokenHash: { type: String, required: true, unique: true, select: false },
    codeHash: { type: String, required: true, select: false },
    codeAttempts: { type: Number, default: 0, select: false },
    // MongoDB removes the row at this instant, so there is nothing to sweep
    // and a forgotten grant cannot linger as a live credential.
    expiresAt: { type: Date, required: true, index: { expires: 0 } },
    usedAt: { type: Date, default: null },
    requestIp: { type: String, default: '' },
    userAgent: { type: String, default: '' },
  },
  { timestamps: true, versionKey: false }
);

/**
 * The filter for "usable right now".
 *
 * A FUNCTION, not a constant, and that is load-bearing. Built once at module load
 * it would capture `new Date()` at require time and then compare every grant's
 * expiry against the moment the process started — so a grant would stay valid
 * for the entire lifetime of the server, and the only thing that ever removed it
 * was MongoDB's TTL sweep (up to 60s later). `validate` and `complete` would
 * both happily honour a link an hour past its expiry.
 *
 * The stubbed tests could not catch this: their fake re-evaluated `Date.now()` on
 * every call, so they agreed with the intent rather than the implementation.
 * See Test File/password-reset-db.test.js.
 */
const activeFilter = () => ({ usedAt: null, expiresAt: { $gt: new Date() } });

passwordResetTokenSchema.statics.store = async function store({
  userId,
  token,
  code,
  ttlMs,
  ip,
  userAgent,
}) {
  return this.create({
    user: userId,
    tokenHash: hashSecret(token),
    codeHash: hashSecret(code),
    expiresAt: new Date(Date.now() + ttlMs),
    requestIp: String(ip || '').slice(0, 64),
    userAgent: String(userAgent || '').slice(0, 200),
  });
};

/** A grant that is usable right now. Returns null for spent/expired/unknown. */
passwordResetTokenSchema.statics.findActiveByTokenHash = function findActiveByTokenHash(rawToken) {
  if (typeof rawToken !== 'string' || rawToken.length < 20) return Promise.resolve(null);
  return this.findOne({ ...activeFilter(), tokenHash: hashSecret(rawToken) });
};

/**
 * Claim a grant, atomically.
 *
 * The `$set` is conditional on `usedAt: null`, so two simultaneous requests
 * with the same link cannot both succeed — MongoDB applies one of them and the
 * loser matches nothing. This is the single-use guarantee, and it has to be a
 * single atomic document update rather than a read followed by a write.
 */
passwordResetTokenSchema.statics.claimByTokenHash = function claimByTokenHash(rawToken) {
  if (typeof rawToken !== 'string' || rawToken.length < 20) return Promise.resolve(null);
  return this.findOneAndUpdate(
    { ...activeFilter(), tokenHash: hashSecret(rawToken) },
    { $set: { usedAt: new Date() } },
    { new: true }
  );
};

/** The most recent usable grant for an account — the one the emailed code is on. */
passwordResetTokenSchema.statics.findLatestActiveForUser = function findLatestActiveForUser(userId) {
  if (!userId) return Promise.resolve(null);
  return this.findOne({ ...activeFilter(), user: userId }).sort({ createdAt: -1 });
};

passwordResetTokenSchema.statics.countActiveForUser = function countActiveForUser(userId) {
  if (!userId) return Promise.resolve(0);
  return this.countDocuments({ ...activeFilter(), user: userId });
};

/**
 * Burn every outstanding grant for an account.
 *
 * Called after a successful reset. Without it, an attacker who triggered a
 * reset BEFORE the real owner did would still hold a working link afterwards —
 * the owner's recovery would not evict them.
 */
passwordResetTokenSchema.statics.invalidateAllForUser = function invalidateAllForUser(userId) {
  if (!userId) return Promise.resolve(null);
  return this.updateMany({ user: userId, usedAt: null }, { $set: { usedAt: new Date() } });
};

/** Drop the oldest live grant, so a burst of requests cannot pile up rows. */
passwordResetTokenSchema.statics.dropOldestActiveForUser = async function dropOldestActiveForUser(userId) {
  if (!userId) return;
  const oldest = await this.findOne({ ...activeFilter(), user: userId }).sort({ createdAt: 1 }).select('_id');
  if (oldest) await this.deleteOne({ _id: oldest._id });
};

/**
 * Compare a submitted 6-digit code against an account's newest live grant.
 *
 * @returns {{ok: true} | {ok: false, outcome: 'no_request'|'expired'|'locked'|'mismatch', record?: object}}
 */
passwordResetTokenSchema.statics.checkCode = async function checkCode(userId, code, maxAttempts) {
  if (!userId) return { ok: false, outcome: 'no_request' };

  const record = await this.findOne({ usedAt: null, user: userId })
    .sort({ createdAt: -1 })
    .select('+codeHash +codeAttempts');
  if (!record) return { ok: false, outcome: 'no_request' };

  if (record.expiresAt && record.expiresAt.getTime() <= Date.now()) {
    return { ok: false, outcome: 'expired', record };
  }

  const attempts = Number(record.codeAttempts) || 0;
  if (attempts >= maxAttempts) {
    await this.updateOne({ _id: record._id }, { $set: { usedAt: new Date() } });
    return { ok: false, outcome: 'locked', record };
  }

  if (!constantTimeEqualsHex(record.codeHash, hashSecret(code))) {
    await this.updateOne({ _id: record._id }, { $inc: { codeAttempts: 1 } });
    return { ok: false, outcome: 'mismatch', record };
  }

  return { ok: true, record };
};

module.exports = mongoose.models.PasswordResetToken
  || mongoose.model('PasswordResetToken', passwordResetTokenSchema);

module.exports.hashSecret = hashSecret;
module.exports.constantTimeEqualsHex = constantTimeEqualsHex;
module.exports.generateSecrets = generateSecrets;
