import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

// ── HTTPS for the dev server ───────────────────────────────────────────────
// Why the certificate is read from disk rather than generated by
// @vitejs/plugin-basic-ssl (which is installed, and was previously commented
// out here with the note "Causes Mixed Content errors with HTTP backend"):
//
// basic-ssl mints a certificate nobody trusts. Browsers and Node both REFUSE an
// untrusted certificate rather than warning about it — `fetch()` to one fails
// outright — so an https dev server holding a basic-ssl certificate produces a
// page that will not load a single module from the API. That is why it was
// disabled, and the mixed-content note was really a trust note.
//
// The certificate here comes from `node scripts/dev-certs.mjs`, which installs a
// local certificate authority into this machine's trust store, so https://localhost
// is genuinely trusted by the browser AND by Node. That is what makes the
// browser page and the API agree on https, with no warning and no error.
//
// Optional on purpose: a clone with no `certs/` directory still starts, over
// HTTP, exactly as before. Requiring the certificate would make a fresh clone
// fail to start for a reason that has nothing to do with the code.
//
// Set VITE_DEV_HTTPS=false to force plain HTTP even when a certificate exists.
const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const CERT_FILE = resolve(REPO_ROOT, 'certs', 'localhost.pem')
const KEY_FILE = resolve(REPO_ROOT, 'certs', 'localhost-key.pem')
const DEV_HTTPS_ENABLED = process.env.VITE_DEV_HTTPS !== 'false'

const devCertificate = DEV_HTTPS_ENABLED && existsSync(CERT_FILE) && existsSync(KEY_FILE)
  ? {
      // Read once at config time rather than per request: these files do not
      // change while the server runs, and a failed read should stop startup,
      // not surface as a TLS error on the first page load.
      cert: readFileSync(CERT_FILE),
      key: readFileSync(KEY_FILE),
    }
  : null

// Whether the API terminates TLS is decided in the SERVER's .env, not in this
// process's environment. Reading `process.env.TLS_ENABLED` alone gets it wrong in
// both directions: this config file is evaluated before Vite's own env loading,
// and the variable that matters lives in a different project's .env file that
// nothing here would otherwise read.
//
// Getting it wrong produces a 502 with no useful cause: proxy target
// `http://localhost:5000` against a server that is answering on
// `https://localhost:5000` is a TLS handshake against a plaintext listener, and
// `https://localhost:5000` against a plaintext server is the reverse. Both read
// as "the API is broken" and neither is.
//
// So the server's .env is parsed here for this one setting. A minimal read
// rather than dotenv: this is a single boolean, the file is a flat KEY=VALUE
// list, and the server is the only thing that writes TLS_ENABLED. An OS-provided
// TLS_ENABLED still wins, matching utils/envFile.js's precedence exactly — so a
// container or CI that sets it externally is not second-guessed by the file.
function serverTlsEnabled() {
  const fromEnvironment = process.env.TLS_ENABLED
  if (fromEnvironment !== undefined) {
    return String(fromEnvironment).trim().toLowerCase() === 'true'
  }
  const envFile = resolve(REPO_ROOT, 'server', '.env')
  if (!existsSync(envFile)) return false
  try {
    for (const line of readFileSync(envFile, 'utf8').split(/\r?\n/)) {
      const match = /^\s*TLS_ENABLED\s*=\s*(.*)$/.exec(line)
      if (!match) continue
      return match[1].trim().replace(/^["']|["']$/g, '').toLowerCase() === 'true'
    }
  } catch {
    // An unreadable .env is not evidence either way; default to plain HTTP,
    // which is what the API serves unless something says otherwise.
    return false
  }
  return false
}

const API_USES_TLS = serverTlsEnabled()
const API_PROXY_TARGET = API_USES_TLS ? 'https://localhost:5000' : 'http://localhost:5000'

// The development CA, for verifying the API's certificate through the proxy.
// Node does not read the OS certificate store (where `mkcert -install` put the
// CA), so without this every proxied request fails the handshake with
// SELF_SIGNED_CERT_IN_CHAIN. Passing the CA keeps verification ON — the
// alternative, `secure: false`, would accept a genuinely wrong certificate, and
// this proxy is the only path by which the browser reaches the API.
const API_PROXY_CA = API_USES_TLS && existsSync(resolve(REPO_ROOT, 'certs', 'rootCA.pem'))
  ? readFileSync(resolve(REPO_ROOT, 'certs', 'rootCA.pem'))
  : null

// ── Response headers the CSP <meta> in index.html structurally cannot carry ──
//
// The policy in index.html covers everything a meta tag is allowed to express.
// `frame-ancestors` is the one that matters here and it is NOT: per spec it is
// IGNORED when delivered in a `<meta http-equiv>` and is honoured only as a real
// response header. Helmet already sets it for the API origin, so without this
// the app origin had no framing protection at all — any site could iframe
// SuppliWise and clickjack it.
//
// Multiple CSP policies are enforced as an INTERSECTION, so shipping a
// frame-ancestors-only header alongside the existing meta policy adds exactly
// this one restriction and nothing else. It is deliberately scoped that way: it
// cannot loosen the meta policy, and it cannot break the app.
//
// SCOPE — read this before assuming production is covered. `vite dev` and
// `vite preview` get these automatically, and scripts/serveDist.mjs imports
// this SAME object for the production `dist/`, so `npm run serve:prod` is
// covered too. If you deploy `dist/` somewhere else (Netlify, Vercel, nginx,
// Cloudflare), that host must send these same headers — copy them from here
// rather than writing a second list, so the policy stays one policy.
export const securityHeaders = {
  'X-Frame-Options': 'DENY',
  'Content-Security-Policy': "frame-ancestors 'none'",
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
}

// https://vite.dev/config/
export default defineConfig(({ command }) => ({
  // `vite build` and `vite dev` otherwise share one node_modules/.vite cache,
  // so a build run while the dev server is up can rewrite state the running
  // server still depends on (observed: orphaned deps_temp_* folders and a
  // deps/ tree that stopped matching the committed metadata). Giving each
  // command its own cache keeps them independent.
  cacheDir: command === 'build' ? 'node_modules/.vite-build' : 'node_modules/.vite',
  // ── If a dependency fails to load in dev ("Failed to fetch dynamically
  // imported module: …/node_modules/.vite/deps/<pkg>.js?v=<hash>"), the fix is:
  //
  //     stop the dev server,  rm -rf node_modules/.vite,  start it again
  //
  // The cause is almost always a package INSTALLED WHILE THE SERVER WAS ALREADY
  // RUNNING. The running optimizer has never pre-bundled it, so the first use
  // forces a re-optimize mid-session; that changes the browser hash, and every
  // `?v=` URL the already-open page holds immediately stops resolving (504).
  // Repeated interrupted runs leave orphaned `node_modules/.vite/deps_temp_*`
  // folders and can end with no committed `deps/` tree at all — which is the
  // state where the server 504s every dependency and nothing renders.
  //
  // Editing a package in node_modules, or `npm install` anything, has the same
  // effect. Restarting is the fix; there is nothing to repair in the config.
  optimizeDeps: {
    // EVERY package that is reached through a DYNAMIC `import()` must be listed
    // here. The startup scan only sees static imports, so a dep first reached at
    // click-time is discovered mid-session, which forces Vite to re-optimize.
    // Re-optimizing changes `browserHash`, and every module URL the loaded page
    // already holds (`...?v=<old hash>`) stops resolving — the server answers
    // 504 "Outdated Optimize Dep", and the browser reports:
    //
    //   Failed to fetch dynamically imported module:
    //   http://localhost:5173/node_modules/.vite/deps/<name>.js?v=<old hash>
    //
    // The page is then stuck: the module it wants is gone, and the fix is a
    // reload nobody thinks to do. (Repeated interrupted re-optimizes also leave
    // orphaned `deps_temp_*` folders behind, which is how a cache ends up
    // without a committed `deps/` tree at all.)
    //
    // Pre-bundling them up front keeps ONE hash for the whole session. Relative
    // imports are unaffected — they are app source, not deps, and need no entry.
    //
    // `optimizeDeps.include` completeness is enforced by
    // src/utils/optimizeDepsInclude.test.js, because this has now bitten twice
    // (jspdf, then @simplewebauthn/browser) and the failure looks like an
    // unrelated browser error rather than a missing config line.
    include: [
      'jspdf',
      'jspdf-autotable',
      // WebAuthn. Imported lazily in api.js so the ~30 KB browser SDK is not in
      // the initial bundle for the majority of people who never touch a passkey.
      '@simplewebauthn/browser',
    ],
    // Node-only packages, reachable solely from `src/**/*.test.js` (those run
    // under `node --test`; only RecoveryPanel.test.js needs these).
    //
    // Excluded because a TEST FILE LIVING INSIDE src/ is enough to pull them
    // into the BROWSER dep cache: anything that makes the dev server transform
    // that file — the dep scanner, a tooling script that walks src/ — registers
    // `vite` and `react-dom/server` as newly discovered browser deps, forces a
    // re-optimize, and moves `browserHash`. Every `?v=` URL a live page holds
    // then 504s, which is the "Failed to fetch dynamically imported module" the
    // note above keeps documenting.
    //
    // Observed doing exactly that: both sat in the committed `_metadata.json`
    // beside the real app deps. Nothing in the browser graph imports them, so
    // excluding changes nothing the app loads.
    //
    // NOTE: excluding is NOT sufficient on its own. The far larger share of this
    // breakage came from that same test file sharing the dev server's CACHE —
    // fixed at the source in RecoveryPanel.test.js and guarded by
    // src/utils/viteCacheIsolation.test.js. This is the second line of defence.
    exclude: [
      'vite',
      'react-dom/server',
    ],
  },
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.svg', 'robots.txt', 'apple-touch-icon.png'],
      manifest: {
        name: 'SuppliWise',
        short_name: 'SuppliWise',
        description: 'AI-powered personalized supplement recommendations and wellness tracking',
        theme_color: '#22c55e',
        background_color: '#f0faf0',
        display: 'standalone',
        orientation: 'portrait-primary',
        scope: '/',
        start_url: '/',
        icons: [
          {
            src: '/pwa-192x192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any'
          },
          {
            src: '/pwa-192x192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'maskable'
          },
          {
            src: '/pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any'
          },
          {
            src: '/pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable'
          }
        ]
      },
      // NEVER enable a service worker against the dev server: a worker running
      // in front of Vite serves cached bundles over live edits — stale pages
      // that no code change could reach until the worker was unregistered.
      // Dev always loads fresh from Vite; only the production build gets a
      // worker (vite-plugin-pwa's own precached one).
      devOptions: {
        enabled: false,
        type: 'module',
        navigateFallback: 'index.html'
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff,woff2}'],
        navigateFallback: null,
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-cache',
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365
              },
              cacheableResponse: {
                statuses: [0, 200]
              }
            }
          },
          {
            urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'gstatic-fonts-cache',
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365
              },
              cacheableResponse: {
                statuses: [0, 200]
              }
            }
          }
          // NOTE: /api responses are intentionally never cached. Caching them
          // caused stale dashboard/intake data (e.g. mark-taken updates
          // appearing not to work until the cache expired).
        ]
      }
    })
  ],
  server: {
    // `host: true` would bind every interface, which would be needed for a phone
    // on the LAN; `localhost` binds loopback only. Left as it was, because
    // widening this changes which machines can reach the dev server and that is
    // a deliberate decision, not a side effect of an HTTPS change.
    host: 'localhost',
    headers: securityHeaders,
    // Fail loudly instead of silently moving to 5174 when something is already
    // holding 5173. A shifted port leaves you reading a stale browser tab
    // pointed at a dead port, and running a second Vite process against the
    // same node_modules/.vite cache corrupts the dependency optimizer.
    strictPort: true,
    // Present only when `certs/` exists. When absent, Vite serves HTTP and
    // nothing here is set.
    ...(devCertificate ? { https: devCertificate } : {}),
    proxy: {
      '/api': {
        // Reads the SERVER's TLS_ENABLED, so the proxy speaks the scheme the API
        // is actually serving. These MUST agree: the browser refuses an https
        // page requesting an http API as mixed content, and a mismatch here
        // surfaces as a 502 on every request with nothing naming the cause.
        target: API_PROXY_TARGET,
        changeOrigin: true,
        // Node trusts its own bundled roots, not the OS certificate store, so
        // without the development CA every proxied request fails the handshake.
        ...(API_PROXY_CA ? { ca: API_PROXY_CA } : {}),
      },
    },
  },
  // `vite preview` serves the real production build, so it needs the same
  // headers as dev. Without this the closest thing to production — the thing you
  // would actually check a build against — was the one origin with no framing
  // protection at all.
  preview: {
    headers: securityHeaders,
    // Same certificate as dev: preview is how you check a build, so it should
    // behave like the deployed thing rather than like a different app.
    ...(devCertificate ? { https: devCertificate } : {}),
  },
}))