/**
 * The plain-language half of a recommendation, for assessments generated by the
 * rule engine rather than the model.
 *
 * WHY THIS FILE EXISTS
 *
 * The AI is asked to return TWO explanations for every recommendation: a
 * clinical `reason` and a plain-language `simplifiedReason` (plus a full
 * citation and a short `simplifiedEvidence`). The reader picks between them
 * with the Simplified / Detailed control.
 *
 * When the AI is unavailable the rule engine takes over — and it filled in six
 * of those fields (evidence, foods, sideEffects, triggeredBy, confidenceScore,
 * severityLevel) but never the two the Simplified view reads. So for roughly one
 * recommendation in five the control did essentially nothing: Simplified fell
 * back to the clinical text and the UI silently stopped meaning what it said.
 *
 * The response shape must not depend on which engine produced it. This module
 * supplies the two missing halves so every record honours the same contract.
 *
 * WHAT THE OUTPUT MUST NOT DO
 *
 *   - invent a symptom, goal or condition. Rule 11 of the prompt says the
 *     "why you" half may only ever be what the patient actually reported, and a
 *     plain-language version that quietly invents a reason is worse than no
 *     plain-language version at all.
 *   - promise an outcome. "May support", never "will fix" or "cures".
 *   - restate the clinical text in shorter words. That is not simplification,
 *     it is the same jargon with fewer syllables.
 *   - say the same thing fifteen times. The driver is matched to the supplement
 *     first, so a plan reads as fifteen distinct reasons rather than one
 *     sentence copied down the page.
 */

/**
 * [keyword, plain benefit, factors it relates to]
 *
 * `factors` are matched against the patient's OWN answers, so they can only
 * ever select something they reported — never introduce anything. The third
 * column is why a plan does not read as the same sentence repeated.
 */
const PLAIN_BENEFITS = [
  // ── Sleep and stress ──
  ['magnesium', 'sleep quality and muscle relaxation', 'sleep,anxiety,stress,muscle,cramp'],
  ['melatonin', 'falling asleep more easily and staying asleep', 'sleep,insomnia'],
  ['ashwagandha', 'stress levels and resilience', 'stress,anxiety,sleep'],
  ['l-theanine', 'a calmer focus without the jitter', 'stress,anxiety,focus'],
  ['theanine', 'a calmer focus without the jitter', 'stress,anxiety,focus'],
  ['bacopa', 'memory and concentration', 'brain fog,memory,focus'],
  ['inositol', 'hormone balance', 'hormone,pcos'],
  ['n-acetyl cysteine', 'a natural liver antioxidant', 'liver,detox'],
  ['nac', 'a natural liver antioxidant', 'liver,detox'],
  ['glycine', 'sleep quality and collagen production', 'sleep,skin'],
  ['tryptophan', 'serotonin and sleep quality', 'sleep,mood,depression'],
  ['5-htp', 'mood and serotonin levels', 'mood,depression,anxiety,sleep'],
  ['apigenin', 'falling asleep more easily', 'sleep,insomnia'],
  ['valerian', 'relaxation and sleep quality', 'sleep,anxiety,stress'],

  // ── Energy and fatigue ──
  ['b12', 'energy when your levels run low', 'fatigue,energy,tingling,brain fog'],
  ['methylcobalamin', 'energy when your levels run low', 'fatigue,energy,tingling'],
  ['b complex', 'converting food into usable energy', 'fatigue,energy,nerve'],
  ['b-complex', 'converting food into usable energy', 'fatigue,energy,nerve'],
  ['coq10', 'heart and muscle energy', 'heart,blood pressure,fatigue,statin'],
  ['ubiquinol', 'heart and muscle energy', 'heart,blood pressure,fatigue'],
  ['riboflavin', 'energy metabolism', 'fatigue,energy,migraine'],
  ['iron bisglycinate', 'carrying oxygen around and beating fatigue', 'fatigue,energy,anemia,dizziness'],
  ['iron', 'carrying oxygen around and beating fatigue', 'fatigue,energy,anemia,dizziness'],
  ['folate', 'cell growth and red blood cells', 'fatigue,anemia,pregnancy'],
  ['folic', 'cell growth and red blood cells', 'fatigue,anemia,pregnancy'],
  ['methylfolate', 'cell growth and red blood cells', 'fatigue,anemia,pregnancy'],
  ['creatine', 'strength, power and recovery', 'muscle,strength,recovery,performance'],
  ['beta-alanine', 'exercise endurance', 'muscle,endurance,performance'],
  ['l-carnitine', 'converting fat into energy', 'fatigue,energy,metabolism'],

  // ── Bones, joints, inflammation ──
  ['collagen', 'skin elasticity, joints and connective tissue', 'joint,skin,hair,nail'],
  ['glucosamine', 'joint comfort and cartilage', 'joint,knee,pain'],
  ['chondroitin', 'joint comfort and cartilage', 'joint,knee,pain'],
  ['curcumin', 'joint comfort and inflammation', 'joint,inflammation,pain'],
  ['turmeric', 'joint comfort and inflammation', 'joint,inflammation,pain'],
  ['tart cherry', 'joint comfort and recovery after exercise', 'joint,recovery,pain'],
  ['resveratrol', 'antioxidant and heart support', 'heart,inflammation'],
  ['boron', 'bone density', 'bone,bone density'],

  // ── Immune ──
  ['zinc', 'immune defence and wound healing', 'cold,immune,wound,skin'],
  ['vitamin c', 'immune defence and collagen production', 'cold,immune,wound,skin'],
  ['vitamin d', 'immune function, bones and mood', 'bone,immune,fatigue,mood'],
  ['selenium', 'thyroid function and antioxidant defence', 'thyroid,immune,skin,hair'],
  ['mushroom', 'immune support', 'immune,energy,fatigue'],
  ['elderberry', 'immune support', 'cold,immune'],
  ['probiotic', 'digestion and gut balance', 'digestion,bloat,gut,ibs'],
  ['digestive enzyme', 'breaking food down so you absorb more', 'digestion,bloat,gut'],
  ['prebiotic', 'the good bacteria in your gut', 'digestion,bloat,gut'],
  ['fiber', 'bowel regularity', 'digestion,constipation,gut'],
  ['fibre', 'bowel regularity', 'digestion,constipation,gut'],

  // ── Skin, hair, nails ──
  ['biotin', 'hair, skin and nail strength', 'hair,skin,nail'],
  ['vitamin e', 'protecting cells from damage', 'skin,immune,heart'],
  ['silica', 'hair, skin and nail strength', 'hair,skin,nail'],

  // ── Heart, blood pressure, blood sugar ──
  ['algae', 'heart health, inflammation and brain function', 'heart,brain fog,inflammation,pregnancy'],
  ['dha', 'brain, eye and heart health', 'brain,eye,pregnancy,cognition'],
  ['epa', 'inflammation and heart health', 'inflammation,heart,joint'],
  ['omega', 'heart health, inflammation and brain function', 'heart,brain fog,inflammation,joint,cholesterol'],
  ['fish oil', 'heart health, inflammation and brain function', 'heart,brain fog,inflammation,joint,cholesterol'],
  ['alpha-lipoic', 'nerve health and how your body handles sugar', 'nerve,blood sugar,neuropathy,diabetes'],
  ['berberine', 'blood sugar and cholesterol', 'blood sugar,cholesterol,weight'],
  ['garlic', 'blood pressure and circulation', 'blood pressure,heart,cholesterol'],
  ['hawthorn', 'heart function and circulation', 'heart,blood pressure'],
  ['citrulline', 'blood flow and exercise performance', 'muscle,endurance,blood flow'],
  ['beetroot', 'blood flow and endurance', 'endurance,stamina,blood flow'],
  ['potassium', 'normal blood pressure and muscle function', 'blood pressure,cramp,muscle'],

  // ── Brain ──
  ["lion's mane", 'focus and nerve regeneration', 'brain fog,focus,memory,mood'],
  ['ginkgo', 'memory and circulation to the brain', 'memory,brain fog,focus'],

  // ── General / multi ──
  ['multivitamin', 'filling everyday nutritional gaps', 'fatigue,immune,energy'],
  ['electrolyte', 'hydration and muscle contractions', 'hydration,cramp,muscle,endurance'],
  ['protein', 'muscle repair and keeping you full', 'muscle,weight,recovery,appetite'],
  ['whey', 'muscle repair and keeping you full', 'muscle,weight,recovery,appetite'],
  ['calcium', 'bone density and muscle contraction', 'bone,cramp,bone density'],
];

/** A reported answer, lowercased so it reads mid-sentence. */
function normalizeAnswer(value) {
  if (typeof value !== 'string') return '';
  return value.trim().toLowerCase();
}

/** The plain benefit for a supplement name, or '' when nothing matches. */
function plainBenefitOf(name) {
  const n = String(name || '').toLowerCase();
  if (!n) return '';
  let best = null;
  for (const [keyword, benefit] of PLAIN_BENEFITS) {
    if (!n.includes(keyword)) continue;
    // Longest match wins, so "vitamin d3 + k2" reads as bone-and-immune
    // support rather than being claimed by a bare "vitamin" entry.
    if (!best || keyword.length > best[0].length) best = [keyword, benefit];
  }
  return best ? best[1] : '';
}

/**
 * The factors this supplement is actually about, or '' when unrecognised.
 */
function factorsOf(name) {
  const n = String(name || '').toLowerCase();
  if (!n) return [];
  let best = null;
  for (const [keyword, , factors] of PLAIN_BENEFITS) {
    if (!n.includes(keyword)) continue;
    if (!best || keyword.length > best.keyword.length) best = { keyword, factors };
  }
  // Defensive on the factor list itself: a table row without one must not take
  // the whole reason down with it.
  return best && typeof best.factors === 'string' ? best.factors.split(',') : [];
}

/** The patient's reported answers, in the order the UI asks for them. */
function reportedAnswers(symptoms, goals, conditions) {
  const take = (list, drop) => (
    (Array.isArray(list) ? list : [])
      .map(normalizeAnswer)
      .filter((item) => item && item !== drop)
  );
  return [
    ...take(symptoms, 'no current symptoms'),
    ...take(goals),
    ...take(conditions, 'none'),
  ];
}

/**
 * The "why you" clause — the patient's OWN words, chosen to relate to this
 * supplement where possible.
 *
 * The supplement's own factors are matched first so fifteen cards do not all
 * end with the same sentence. The first reported answer is the fallback, and
 * only a reported answer is ever used: nothing here can introduce a symptom,
 * goal or condition the patient did not give.
 */
function plainDriverOf(symptoms, goals, conditions, name) {
  const answers = reportedAnswers(symptoms, goals, conditions);
  if (answers.length === 0) return '';

  const factors = factorsOf(name);
  if (factors.length > 0) {
    for (const factor of factors) {
      const hit = answers.find((answer) => answer.includes(factor));
      if (hit) return hit;
    }
  }
  return answers[0];
}

/**
 * One plain sentence: what it is for, and why it is for THIS person.
 *
 * @param {{name?: string, symptoms?: string[], goals?: string[], conditions?: string[]}} rec
 * @returns {string} '' when the supplement is not recognised
 */
function simplifiedReasonFor(rec) {
  if (!rec || typeof rec !== 'object') return '';
  const benefit = plainBenefitOf(rec.name);
  if (!benefit) return '';

  const driver = plainDriverOf(rec.symptoms, rec.goals, rec.conditions, rec.name);
  if (!driver) return `Helps support ${benefit}.`;
  return `Helps support ${benefit} — you reported ${driver}.`;
}

/**
 * A short, non-technical stand-in for the citation. Deliberately vague about
 * the study and honest about its existence: the reader is told the claim is
 * researched, and the full citation one toggle away.
 */
function simplifiedEvidenceFor(name) {
  const benefit = plainBenefitOf(name);
  if (!benefit) return '';
  // Under a dozen words. The full source is in the Detailed view; repeating it
  // here in shorter words is the thing this file exists to avoid.
  const short = benefit.split(/,| and /)[0].trim();
  return `Research supports this for ${short}.`;
}

module.exports = {
  PLAIN_BENEFITS,
  plainBenefitOf,
  plainDriverOf,
  factorsOf,
  simplifiedReasonFor,
  simplifiedEvidenceFor,
};
